[global]
mode = spoke
interface = dtun0
local_outer_ip = 0.0.0.0
probe_interval_ms = 1000
path_timeout_ms = 3000
fast_recovery = true
node_id = 2
address = 10.99.0.2/24
psk = 00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff

[spoke]
hub_address = 192.0.2.1
hub_port = 49001
refresh_interval_ms = 1000
