#ifndef DTUN_UAPI_H
#define DTUN_UAPI_H

enum dtun_nl_cmd {
  DTUN_CMD_UNSPEC,
  DTUN_CMD_PEER_ADD,
  DTUN_CMD_PEER_DEL,
  DTUN_CMD_PEER_SET,
  DTUN_CMD_ROUTE_ADD,
  DTUN_CMD_ROUTE_DEL,
  DTUN_CMD_PEER_GET,
  DTUN_CMD_STATS_GET,
  DTUN_CMD_PEER_LIST,
  DTUN_CMD_REBIND,
  DTUN_CMD_HUB_SET,
  DTUN_CMD_HUB_MIGRATE,
  DTUN_CMD_ROLE_SET,
  __DTUN_CMD_MAX,
};
#define DTUN_CMD_MAX (__DTUN_CMD_MAX - 1)

enum dtun_nl_attr {
  DTUN_A_UNSPEC,
  DTUN_A_IFINDEX,
  DTUN_A_TUNNEL_ID,
  DTUN_A_NODE_ID,
  DTUN_A_RAW_ADDR,
  DTUN_A_UDP_ADDR,
  DTUN_A_UDP_PORT,
  DTUN_A_KEY,
  DTUN_A_PREFIX,
  DTUN_A_PREFIX_LEN,
  DTUN_A_PATH,
  DTUN_A_RAW_UP,
  DTUN_A_UDP_UP,
  DTUN_A_REMOTE_TUNNEL_ID,
  DTUN_A_DYNAMIC_RAW,
  DTUN_A_CANDIDATE_GENERATION,
  DTUN_A_RENDEZVOUS_UDP_ADDR,
  DTUN_A_RENDEZVOUS_UDP_PORT,
  DTUN_A_DIRECT_UDP_ADDR,
  DTUN_A_DIRECT_UDP_PORT,
  DTUN_A_RAW_VALIDATED_ADDR,
  DTUN_A_SELECTED_PATH,
  DTUN_A_HUB_ADDR,
  DTUN_A_HUB_PORT,
  DTUN_A_HUB_TERM,
  DTUN_A_OPERATIONAL,
  DTUN_A_RAW_HEALTH,
  DTUN_A_UDP_HEALTH,
  DTUN_A_RAW_SRTT_US,
  DTUN_A_UDP_SRTT_US,
  DTUN_A_RAW_RTTVAR_US,
  DTUN_A_UDP_RTTVAR_US,
  DTUN_A_RAW_LOSS_PPM,
  DTUN_A_UDP_LOSS_PPM,
  DTUN_A_RAW_THRESHOLD_MS,
  DTUN_A_UDP_THRESHOLD_MS,
  DTUN_A_RAW_LAST_ACK_MS,
  DTUN_A_UDP_LAST_ACK_MS,
  __DTUN_A_MAX,
};
#define DTUN_A_MAX (__DTUN_A_MAX - 1)

enum dtun_link_attr {
  IFLA_DTUN_UNSPEC,
  IFLA_DTUN_LOCAL,
  IFLA_DTUN_UDP_PORT,
  IFLA_DTUN_NODE_ID,
  IFLA_DTUN_HUB,
  IFLA_DTUN_HUB_PORT,
  IFLA_DTUN_PROBE_INTERVAL_MS_RESERVED,
  IFLA_DTUN_PATH_TIMEOUT_MS_RESERVED,
  __IFLA_DTUN_MAX,
};
#define IFLA_DTUN_MAX (__IFLA_DTUN_MAX - 1)

enum dtun_selected_path {
  DTUN_PATH_DOWN = 0,
  DTUN_PATH_RAW = 1,
  DTUN_PATH_UDP = 2,
  DTUN_PATH_HUB = 3,
};

enum dtun_health_state {
  DTUN_HEALTH_UNKNOWN = 0,
  DTUN_HEALTH_HEALTHY = 1,
  DTUN_HEALTH_SUSPECT = 2,
  DTUN_HEALTH_OFFLINE = 3,
};

#endif /* DTUN_UAPI_H */
